package eu.someplacee.lobby.enums;

public enum CustomSkull {
    JUSTDESTOX, JAVABUCH, MODERSTOR, MUTEKIMEHJR, BAUMBLAU, NURNILS, KXTHI, IBKYT, KASIUX, GOMMEHD, REWINSIDE, UNGESPIELT, ROTPILZ, PETRIT, BYQUADRIX, POISHII, PUBLICMOSS, BACK, NEXT, QUESTION, EXCLAMATION, KING;
}
